PhotoApp/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :posts do
    resources :reviews
  end
  resources :tags, only: [:show]
  resources :locations, only: [:show]

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users

end

PhotoApp/app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :tags, through: :posts
  has_many :locations, through: :posts
  
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: URI::MailTo::EMAIL_REGEXP, message: "only allows valid emails" },
    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

def count_posts
   self.posts.length
 end

 def avg_likes_per_post
   sum = 0
   self.posts.each do |post|
     sum += post.count_likes
   end
   sum.to_f / self.count_posts
 end

 def count_posts_you_like
   sum = 0
   self.reviews.each do |review|
     if review.like
       sum += 1
     end
   end
   sum
 end

 def favorite_tag
   tags = self.posts.map {|post| post.tag.name }
   freq = tags.inject(Hash.new(0)) { |h,v| h[v] += 1; h }
   fav_tag = tags.max_by { |v| freq[v] }
   if freq.values.count(freq[fav_tag]) > 1
     max = freq[fav_tag]
     favs = tags.select {|tag| freq[tag]==max}
     "##{favs.join(', #')}"
   else
     "##{fav_tag}"
   end
 end

 def favorite_location
   locations = self.posts.map {|post| post.location.name }
   freq = locations.inject(Hash.new(0)) { |h,v| h[v] += 1; h }
   fav_location = locations.max_by { |v| freq[v] }
   if freq.values.count(freq[fav_location]) > 1
     max = freq[fav_location]
     favs = locations.select {|location| freq[location]==max}
     "#{favs.join(', ')}"
   else
     "#{fav_location}"
   end
 end

end

PhotoApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index, :destroy]
  before_action :correct_user,   only: [:edit, :update]

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the PhotosApp!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "Your account was deleted"
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

PhotoApp/app/helpers/users_helper.rb
module UsersHelper
end

PhotoApp/app/views/users/_form.html.erb
<%= form_for @user, html: { multipart: true } do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  <div class="b-margin">
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  </div>
<% end %>

PhotoApp/app/views/users/edit.html.erb
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <%= link_to "Delete Account", @user, method: :delete, data: {confirm: "Are you sure you want to delete your account?"}, class: "btn btn-danger", style: "margin-top: 20px;" %>
  </div>
</div>

PhotoApp/app/views/users/index.html.erb
<h1>DunderGram</h1>
<% @users.each do |user| %>
 <p><%=link_to user.name, user_path(user)%> - <%= user.email %></p>
<% end %>

PhotoApp/app/views/users/new.html.erb
<% provide(:button_text, 'Sign Up!') %>
<h1>Sign Up</h1>
<%= render 'form' %>

PhotoApp/app/views/users/show.html.erb
<div class="row text-center">
  <div class="col col-sm-3">
    <h4><%= @user.name %></h4>
  </div>
  <div class="col col-sm-3">
    <h4><%= @user.email %></h4>
  </div>
  <div class="col col-sm-3">
    <h4>Number of Posts: <%= @user.count_posts %></h4>
  </div>
  <div class="col col-sm-3">
    <% if logged_in? %>
      <%= link_to "New Post", new_post_path, class: "btn btn-success" %>
    <% end %>
  </div>
</div>

<div>
  <ul>
    <li>Avg likes per post: <%= @user.avg_likes_per_post%></li>
    <li>You liked <%= @user.count_posts_you_like%> photo(s)</li>
    <li>Favorite Tag(s): <%= @user.favorite_tag %></li>
    <li>Most Frequent Location(s): <%= @user.favorite_location%></li>
  </ul>
</div>

<div class="row">
  <% @user.posts.each do |post| %>
    <div class="col-md-4 text-center b-margin">
      <%=link_to (image_tag post.post_img.url(:medium)), post_path(post) %>
    </div>
  <% end %>
</div>

<% if logged_in? && @user.id == current_user.id %>
  <%= button_to "Edit User", edit_user_path(@user), :method => "get", class: "btn btn-primary b-margin" %>
<% end %>