PhotoApp/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :posts do
    resources :reviews
  end
  resources :tags, only: [:show]
  resources :locations, only: [:show]

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users

end

PhotoApp/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :tag
  belongs_to :location
  has_many :reviews
  has_attached_file :post_img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :post_img, content_type: /\Aimage\/.*\z/

  def count_likes
    sum = 0
    self.reviews.each do |rev|
      if rev.like
        sum += 1
      end
    end
    sum
  end

end

PhotoApp/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = current_user.posts.build
    # @post = Post.new
    # @users = User.all
    # @locations = Location.all
    # @tags = Tag.all
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @reviews = @post.reviews
    @users = User.all
  end

  def create
    @post = current_user.posts.build(post_params)
    # @post = Post.new(post_params)
    @tag = Tag.find_or_create_by(name: params[:post][:tag])
    @post.tag_id = @tag.id 
    @location = Location.find_or_create_by(name: params[:post][:location])
    @post.location_id = @location.id
    if @post.valid?
      @post.save
      redirect_to post_path(@post)
    else
      redirect_to 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
    @user = @post.user 
    @tag = @post.tag
    @location = @post.location
  end

  def update
    @post = Post.find(params[:id])
    @tag = Tag.find_or_create_by(name: params[:post][:tag])
    @post.tag_id = @tag.id 
    @location = Location.find_or_create_by(name: params[:post][:location])
    @post.location_id = @location.id
    @post.update(post_params)
    redirect_to @post
  end

  def destroy
    @post = Post.find(params[:id]).destroy
    redirect_to user_path(current_user)
  end

  private
    def post_params
      params.require(:post).permit(:caption, :user_id, :tag_id, :location_id, :post_img)
    end

    def find_post
      @post = Post.find(params[:id])
    end
end

PhotoApp/app/helpers/posts_helper.rb
module PostsHelper
end

PhotoApp/app/views/posts/_form.html.erb
<div class="container">
  <%= form_for @post, html: { multipart: true } do |f| %>

    <%= f.file_field :post_img %><br />

    <%= f.label :caption %><br />
    <%= f.text_field :caption, class: "form-control" %><br />

    <%= f.label :tag %>
   <p>#<%= f.text_field :tag, class: "form-control" %><br /></p>

    <%= f.label :location %><br />
    <%= f.text_field :location, class: "form-control" %><br />

    <%= f.submit %>
    
  <% end %>

</div>

PhotoApp/app/views/posts/edit.html.erb
<h1>Post Edit</h1>

<div class="container">
 <%= form_for @post, html: { multipart: true } do |f| %>

   <br>

   <%= f.file_field :post_img %><br />

   <%= f.label :caption %><br />
   <%= f.text_field :caption, class: "form-control" %><br />

   <%= f.label :tag %>
  <p>#<%= f.text_field :tag, value: @tag.name, class: "form-control" %><br /></p>

   <%= f.label :location %><br />
   <%= f.text_field :location, value: @location.name, class: "form-control" %><br />

   <%= f.submit %>
 <% end %>

 <%= form_for @post, method: :delete do |f| %>
 <%= f.submit "Delete"%> <br />
 <% end %>
</div>

PhotoApp/app/views/posts/index.html.erb
<h1>Dunder Mifflin Posts</h1>
<div class="row">
  <% @posts.each do |post| %>
    <div class="col-md-4 text-center b-margin">
      <%= link_to (image_tag post.post_img.url(:medium)), user_path(post.user_id), class: "img-responsive imw" %>
    </div>
  <% end %>
</div>

PhotoApp/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

PhotoApp/app/views/posts/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-12">

      <%= image_tag @post.post_img.url(:medium), class: "photo img-responsive img-rounded" %>

    </div>
  </div>

  <div class="row">
    <div class="col-md-12">

      <p class="well text-center caption"><%= @post.caption %></p>
      <p class="text-right user-name">Poster: <%= link_to @post.user.name, user_path(@post.user) %></p>

    </div>
  </div>

  <div class="row">
    <div class="col-sm-6 text-center">

      <p>#<%= link_to @post.tag.name, tag_path(@post.tag_id) %></p>
    </div>

    <div class="col-sm-6 text-center">

      <p>Location: <%= link_to @post.location.name, location_path(@post.location_id) %>
      </p>
      <% if logged_in? && @post.user_id == current_user.id %>
        <%= button_to "Edit Post", edit_post_path(@post), :method => "get", class: "btn btn-primary b-margin" %>
      <% end %>
    </div>
  </div>
  
  <p>Number of likes: <%= @post.count_likes %></p>

  <p>Comments:</p>
  <ul>
    <% @reviews.each do |rev| %>
      <li><%= rev.user.name %> - <%= rev.comment %></li>
      <% if logged_in? && rev.user_id == current_user.id %>
    <%= button_to "Edit Comment", edit_post_review_path(rev.user,rev), :method => "get", class: "btn btn-primary b-margin" %>
     <%= link_to "Delete", [@post, rev], :method  => :delete, class: "btn btn-danger b-margin" %>
      <% end %>
    <% end %>
  </ul>

  <% if logged_in? %>
    <%= render 'reviews/form' %>
  <% end %>

</div>