PhotoApp/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :posts do
    resources :reviews
  end
  resources :tags, only: [:show]
  resources :locations, only: [:show]

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users

end

PhotoApp/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    
    <div class="navbar-header">
      <%= link_to "DunderGram", root_path, class: "navbar-brand" %>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "All Photos", posts_path %></li>
      <li><%= link_to "All Employees", users_path %></li>
      <% if logged_in? %>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Sign Out", logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_path %></li>
        <li><%= link_to "Log In", login_path %></li>
      <% end %>
    </ul>

  </div>
</nav>

PhotoApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DunderGram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">

    <%= yield %>

    </div>
    
  </body>
</html>